name: 'Setup OpenVPN connection'
description: 'Connect Github Actions to VPN'
author: nanopx
branding:
  color: green
  icon: globe
inputs:
  ovpnConfig:
    required: false
    description: 'Content of .ovpn config file (Required when disconnect is false)'
  username:
    required: false
    description: 'OpenVPN username'
  password:
    required: false
    description: 'OpenVPN password'
  disconnect:
    required: false
    description: 'Disconnect from VPN'
  domains:
    required: false
    description: 'Use VPN for specified domains'
  pid:
    required: false
    description: 'OpenVPN process ID (Required when disconnect is true)'
outputs:
  pid:
    description: 'OpenVPN process ID'
runs:
  using: 'node20'
  main: 'packages/action/dist/index.js'
  post: 'packages/action/dist/index.js'
