name: 'Setup OpenVPN connection'
description: 'Connect Github Actions to VPN'
author: nanopx
branding:
  color: green
  icon: globe
inputs:
  ovpnConfig:
    required: true
    description: 'Content of .ovpn config file'
  username:
    required: false
    description: 'OpenVPN username'
  password:
    required: false
    description: 'OpenVPN password'
# outputs:
runs:
  using: 'node20'
  main: 'packages/action/dist/index.js'
  post: 'packages/action/dist/index.js'
