name: 'test-domains'

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install OpenVPN
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install -y openvpn

      - name: Get public IP
        run: |
          curl -m 5 'https://api64.ipify.org?format=json'

      - name: Connect to VPN
        uses: ./
        id: ovpn
        with:
          ovpnConfig: ${{ secrets.OVPN_CONFIG }}
          username: ${{ secrets.OVPN_USERNAME }}
          password: ${{ secrets.OVPN_PASSWORD }}
          domains: |-
            api64.ipify.org

      - name: Get public IP
        run: |
          curl -m 5 'https://api64.ipify.org?format=json'

  test-ignored:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn

      - name: Get public IP
        run: |
          curl -m 5 'https://api64.ipify.org?format=json'

      - name: Connect to VPN
        uses: ./
        id: ovpn
        with:
          ovpnConfig: ${{ secrets.OVPN_CONFIG }}
          username: ${{ secrets.OVPN_USERNAME }}
          password: ${{ secrets.OVPN_PASSWORD }}
          domains: |-
            google.com

      - name: Get public IP
        run: |
          curl -m 5 'https://api64.ipify.org?format=json'
        